In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/digit-recognizer/sample_submission.csv
/kaggle/input/competitions/digit-recognizer/train.csv
/kaggle/input/competitions/digit-recognizer/test.csv

In [2]:

df = pd.read_csv('/kaggle/input/competitions/digit-recognizer/train.csv')

In [3]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
X= df.drop(columns=['label'])
y=df['label']

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42, stratify= y)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [7]:
clf1= LogisticRegression()
clf2= DecisionTreeClassifier()

In [8]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [9]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score, confusion_matrix
print('Accuracy_score of Logistic_Regression:', accuracy_score(y_test,y_pred1))
print('Accuracy_score of Decision_Tree:', accuracy_score(y_test,y_pred2))

Accuracy_score of Logistic_Regression: 0.9110714285714285
Accuracy_score of Decision_Tree: 0.8555952380952381

In [11]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  787    0    6    3    4    7   11    0    7    2
1    0  919    2    4    0    2    0    0    9    1
2    3   10  747   18   10    7    7   10   20    3
3    4    5   27  768    0   32    4    7   16    7
4    3    3    6    0  742    4    4    4   11   37
5   12    6   10   30   12  638   10    2   31    8
6    5    3    5    0    5   10  794    1    4    0
7    1    3    5    6    7    1    1  815    5   36
8    7   23   11   22    6   26    8    2  689   19
9    4    4    3   10   22    5    0   30    6  754

In [12]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  751    0   10    6    6   13   19    8   10    4
1    0  892    5   10    2    4    5    4   10    5
2   10   12  706   24   10    4    9   17   31   12
3   17    6   27  712   10   36    4   14   22   22
4    7    7   13    3  689   10    9    9   12   55
5   10    3   12   49   12  597   23    6   26   21
6    7    3   10    7   11   20  752    1   15    1
7    2    7   21   21    9    6    0  785    7   22
8    5   21   30   31   20   35   17   10  618   26
9    7    2   15   14   43   21    6   29   16  685

In [13]:
from sklearn.metrics import precision_score, recall_score, f1_score
print('Precision_score of Logistic_Regression:', precision_score(y_test,y_pred1, average='weighted'))
print('Precision_score of Decision_Tree:', precision_score(y_test,y_pred2, average='weighted'))

Precision_score of Logistic_Regression: 0.9108227006609134
Precision_score of Decision_Tree: 0.8552532972796666

In [14]:
print('Recall_score of Logistic_Regression:', recall_score(y_test,y_pred1, average='weighted'))
print('Recall_score of Decision_Tree:', recall_score(y_test,y_pred2, average='weighted'))

Recall_score of Logistic_Regression: 0.9110714285714285
Recall_score of Decision_Tree: 0.8555952380952381

In [15]:
print('F1_score of Logistic_Regression:', f1_score(y_test,y_pred1, average='weighted'))
print('F1_score of Decision_Tree:', f1_score(y_test,y_pred2, average='weighted'))

F1_score of Logistic_Regression: 0.9108277300418286
F1_score of Decision_Tree: 0.8553200635095666

In [16]:
from sklearn.metrics import classification_report
print('Classification Report of Logistic_Regression:')
print(classification_report(y_test,y_pred1))

Classification Report of Logistic_Regression:
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       827
           1       0.94      0.98      0.96       937
           2       0.91      0.89      0.90       835
           3       0.89      0.88      0.89       870
           4       0.92      0.91      0.91       814
           5       0.87      0.84      0.86       759
           6       0.95      0.96      0.95       827
           7       0.94      0.93      0.93       880
           8       0.86      0.85      0.86       813
           9       0.87      0.90      0.88       838

    accuracy                           0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400

In [17]:
from sklearn.metrics import classification_report
print('Classification Report of Decision Tree:')
print(classification_report(y_test,y_pred2))

Classification Report of Decision Tree:
              precision    recall  f1-score   support

           0       0.92      0.91      0.91       827
           1       0.94      0.95      0.94       937
           2       0.83      0.85      0.84       835
           3       0.81      0.82      0.82       870
           4       0.85      0.85      0.85       814
           5       0.80      0.79      0.79       759
           6       0.89      0.91      0.90       827
           7       0.89      0.89      0.89       880
           8       0.81      0.76      0.78       813
           9       0.80      0.82      0.81       838

    accuracy                           0.86      8400
   macro avg       0.85      0.85      0.85      8400
weighted avg       0.86      0.86      0.86      8400