In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/uciml/iris/Iris.csv
/kaggle/input/datasets/uciml/iris/database.sqlite

In [2]:
df = pd.read_csv('/kaggle/input/datasets/uciml/iris/Iris.csv')

In [3]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Species'] = encoder.fit_transform(df['Species'])

In [5]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [6]:
X = df.drop(columns=['Species'])
y = df['Species']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 2)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [9]:
LR = LogisticRegression()
DTC = DecisionTreeClassifier()

In [10]:
LR.fit(X_train, y_train)
DTC.fit(X_train, y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [11]:
y_pred1 = LR.predict(X_test)
y_pred2 = DTC.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix, precision_score,recall_score,f1_score

In [13]:
print("Accuracy Score of Logistic Regression", accuracy_score(y_test, y_pred1))
print("Accuracy Score of DecisionTreeClassifier", accuracy_score(y_test, y_pred2))

Accuracy Score of Logistic Regression 1.0
Accuracy Score of DecisionTreeClassifier 1.0

In [14]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test, y_pred1), columns = list(range(0,3)))

Logistic Regression Confusion Matrix

    0  1  2
0  14  0  0
1   0  8  0
2   0  0  8

In [15]:
print("DecisionTreeClassifier Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test, y_pred2), columns = list(range(0,3)))

DecisionTreeClassifier Confusion Matrix

    0  1  2
0  14  0  0
1   0  8  0
2   0  0  8

In [16]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2
result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
128             2                               2                         2
2               0                               0                         0
35              0                               0                         0
77              1                               1                         1
54              1                               1                         1
129             2                               2                         2
108             2                               2                         2
25              0                               0                         0
74              1                               1                         1
48              0                               0                         0

In [17]:
from sklearn.metrics import precision_score,recall_score
precision_score(y_test,y_pred1,average=None)

array([1., 1., 1.])

In [18]:
recall_score(y_test,y_pred1,average=None)

array([1., 1., 1.])

In [19]:
from sklearn.metrics import classification_report
print('Classification Report of Logistic_Regression:')
print(classification_report(y_test,y_pred1))

Classification Report of Logistic_Regression:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [20]:
from sklearn.metrics import classification_report
print('Classification Report of DecisionTreeClassifier:')
print(classification_report(y_test,y_pred2))

Classification Report of DecisionTreeClassifier:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30